### ISSUE TITLE
Connection to Occi-OS and Openstack

### ISSUE THREAD

**Issue by Alex134** [gwdg/rOCCI-api#37]
Hi,

I'm trying to use Rocci-api ton connect to a server that runs OpenStack and Occi-os
```ruby
require 'rubygems'
require 'pp'
require 'occi-api'
USERNAME = 'admin'
PASSWORD = 'supersecret'
ENDPOINT = 'http://192.168.52.163:8787/'
auth = Hashie::Mash.new
auth.type = 'basic'
auth.username = USERNAME
auth.password = PASSWORD
options = {
  :endpoint => ENDPOINT,
  :auth => auth,
  :log => {:out => STDERR, :level => Occi::Api::Log::WARN, :logger => nil},
  :auto_connect => true,
  :media_type => nil
}
puts 'test'
client = Occi::Api::Client::ClientHttp.new(options ||= {})
puts 'test2'
```
But this generates an error:
```
/var/lib/gems/1.9.1/gems/occi-api-4.3.1/lib/occi/api/client/http/authn_plugins/keystone.rb:110:in `get_first_working_tenant': Keystone didn't return any tenants, fallback failed! (Occi::Api::Client::Errors::AuthnError)
from /var/lib/gems/1.9.1/gems/occi-api-4.3.1/lib/occi/api/client/http/authn_plugins/keystone.rb:20:in `setup'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.1/lib/occi/api/client/http/helpers.rb:39:in `get_auth'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.1/lib/occi/api/client/http/helpers.rb:56:in `rescue in preauthenticate'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.1/lib/occi/api/client/http/helpers.rb:46:in `preauthenticate'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.1/lib/occi/api/client/client_base.rb:44:in `initialize'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.1/lib/occi/api/client/client_http.rb:46:in `initialize'
	from occi_test.rb:26:in `new'
	from occi_test.rb:26:in `<main>'
```

I checked with "keystone tenant-list" and this doesn't seems to come from the cloud.
Can someone help me find the origin of this error ?

Thanks :)

**Comment by arax** [comment]
Hi,

for future reference, this https://github.com/EGI-FCTF/rOCCI-api is the central repo, if you could open any subsequent issues there, it would be great.

Could you, please, make the following change (to enable debugging)?

```ruby
:log => { :out => STDERR, :level => Occi::Api::Log::DEBUG, :logger => nil },
```
Please, be careful, output will contain sensitive information (passwords, server addresses, etc.).

Cheers

**Comment by Alex134** [comment]
Thanks for the response, Here's the output:
```
opening connection to 192.168.52.163...
opened
<- "HEAD /-/ HTTP/1.1\r\nAccept: text/plain,text/occi;q=0.2\r\nUser-Agent: rOCCI-core/4.3.2 rOCCI-api/4.3.1 OCCI/1.1 ruby-x86_64-linux/1.9.3p484\r\nAuthorization: Basic YWRtaW46c3VwZXJzZWNyZXQ=\r\nConnection: close\r\nHost: 192.168.52.163:8787\r\n\r\n"
-> "HTTP/1.1 401 Unauthorized\r\n"
-> "Www-Authenticate: Keystone uri='http://192.168.52.163:35357'\r\n"
-> "Content-Type: text/plain\r\n"
-> "Content-Length: 0\r\n"
-> "Date: Tue, 10 Mar 2015 17:34:22 GMT\r\n"
-> "Connection: close\r\n"
-> "\r\n"
Conn close
D, [2015-03-10T10:34:22.403125 #68442] DEBUG -- : [rOCCI-api] Authentication failed with code 401!
opening connection to 192.168.52.163...
opened
<- "HEAD /-/ HTTP/1.1\r\nAccept: text/plain,text/occi;q=0.2\r\nUser-Agent: rOCCI-core/4.3.2 rOCCI-api/4.3.1 OCCI/1.1 ruby-x86_64-linux/1.9.3p484\r\nAuthorization: Basic YWRtaW46c3VwZXJzZWNyZXQ=\r\nConnection: close\r\nHost: 192.168.52.163:8787\r\n\r\n"
-> "HTTP/1.1 401 Unauthorized\r\n"
-> "Www-Authenticate: Keystone uri='http://192.168.52.163:35357'\r\n"
-> "Content-Type: text/plain\r\n"
-> "Content-Length: 0\r\n"
-> "Date: Tue, 10 Mar 2015 17:34:22 GMT\r\n"
-> "Connection: close\r\n"
-> "\r\n"
Conn close
D, [2015-03-10T10:34:22.420693 #68442] DEBUG -- : [rOCCI-api] #<HTTParty::Response:0x8 parsed_response=nil, @response=#<Net::HTTPUnauthorized 401 Unauthorized readbody=true>, @headers={"www-authenticate"=>["Keystone uri='http://192.168.52.163:35357'"], "content-type"=>["text/plain"], "content-length"=>["0"], "date"=>["Tue, 10 Mar 2015 17:34:22 GMT"], "connection"=>["close"]}>
opening connection to 192.168.52.163...
opened
<- "POST /v2.0/tokens HTTP/1.1\r\nAccept: application/json\r\nUser-Agent: rOCCI-core/4.3.2 rOCCI-api/4.3.1 OCCI/1.1 ruby-x86_64-linux/1.9.3p484\r\nContent-Type: application/json\r\nAuthorization: Basic YWRtaW46c3VwZXJzZWNyZXQ=\r\nConnection: close\r\nHost: 192.168.52.163:35357\r\nContent-Length: 78\r\n\r\n"
<- "{\"auth\":{\"passwordCredentials\":{\"username\":\"admin\",\"password\":\"supersecret\"}}}"
-> "HTTP/1.1 200 OK\r\n"
-> "Vary: X-Auth-Token\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 1317\r\n"
-> "Date: Tue, 10 Mar 2015 17:34:22 GMT\r\n"
-> "Connection: close\r\n"
-> "\r\n"
reading 1317 bytes...
-> "{\"access\": {\"token\": {\"issued_at\": \"2015-03-10T17:34:22.652151\", \"expires\": \"2015-03-10T18:34:22Z\", \"id\": \"MIIC+QYJKoZIhvcNAQcCoIIC6jCCAuYCAQExDTALBglghkgBZQMEAgEwggFHBgkqhkiG9w0BBwGgggE4BIIBNHsiYWNjZXNzIjogeyJ0b2tlbiI6IHsiaXNzdWVkX2F0IjogIjIwMTUtMDMtMTBUMTc6MzQ6MjIuNjUyMTUxIiwgImV4cGlyZXMiOiAiMjAxNS0wMy0xMFQxODozNDoyMloiLCAiaWQiOiAicGxhY2Vob2xkZXIifSwgInNlcnZpY2VDYXRhbG9nIjogW10sICJ1c2VyIjogeyJ1c2VybmFtZSI6ICJhZG1pbiIsICJyb2xlc19saW5rcyI6IFtdLCAiaWQiOiAiMjY0OTE2NTE3MjkyNDc5NjkxMzk4MDYxMTY2Y2FkNTkiLCAicm9sZXMiOiBbXSwgIm5hbWUiOiAiYWRtaW4ifSwgIm1ldGFkYXRhIjogeyJpc19hZG1pbiI6IDAsICJyb2xlcyI6IFtdfX19MYIBhTCCAYECAQEwXDBXMQswCQYDVQQGEwJVUzEOMAwGA1UECAwFVW5zZXQxDjAMBgNVBAcMBVVuc2V0MQ4wDAYDVQQKDAVVbnNldDEYMBYGA1UEAwwPd3d3LmV4YW1wbGUuY29tAgEBMAsGCWCGSAFlAwQCATANBgkqhkiG9w0BAQEFAASCAQAFH5pNJBnDaE08xNCq7GXcC+lPMgD3ZNOZDXAXTTKerSq3qSGF+HGQYMXlIUQsCTwTKRflumA+gFVlt4I51fXDNdbk0cgCVuzRa0YmZY829UfXbwPaRmhYRm46CPhvrS4ven8Nu2SF1ON+uK2nnqgwXLjXAwEjPnUdWQ-SfW5roPGlN6prcOUdshO2GfzWrbjl-iCsS36-3C5PVnJabO0ypKr+bBy-HGuN2sL40yXOx6tSqt6YY7wzpwQG2pCzmVc3A3lF19g5VZTGe0apBbnYc8MKXGA24uNLssRUGHd-OjVWr95dQOxiaUbvEGs2u2o18PKbvvEZdqy8fT0LKXGh\"}, \"serviceCatalog\": [], \"user\": {\"username\": \"admin\", \"roles_links\": [], \"id\": \"264916517292479691398061166cad59\", \"roles\": [], \"name\": \"admin\"}, \"metadata\": {\"is_admin\": 0, \"roles\": []}}}"
read 1317 bytes
Conn close
D, [2015-03-10T10:34:22.733334 #68442] DEBUG -- : [rOCCI-api] #<HTTParty::Response:0x1730180 parsed_response={"access"=>{"token"=>{"issued_at"=>"2015-03-10T17:34:22.652151", "expires"=>"2015-03-10T18:34:22Z", "id"=>"MIIC+QYJKoZIhvcNAQcCoIIC6jCCAuYCAQExDTALBglghkgBZQMEAgEwggFHBgkqhkiG9w0BBwGgggE4BIIBNHsiYWNjZXNzIjogeyJ0b2tlbiI6IHsiaXNzdWVkX2F0IjogIjIwMTUtMDMtMTBUMTc6MzQ6MjIuNjUyMTUxIiwgImV4cGlyZXMiOiAiMjAxNS0wMy0xMFQxODozNDoyMloiLCAiaWQiOiAicGxhY2Vob2xkZXIifSwgInNlcnZpY2VDYXRhbG9nIjogW10sICJ1c2VyIjogeyJ1c2VybmFtZSI6ICJhZG1pbiIsICJyb2xlc19saW5rcyI6IFtdLCAiaWQiOiAiMjY0OTE2NTE3MjkyNDc5NjkxMzk4MDYxMTY2Y2FkNTkiLCAicm9sZXMiOiBbXSwgIm5hbWUiOiAiYWRtaW4ifSwgIm1ldGFkYXRhIjogeyJpc19hZG1pbiI6IDAsICJyb2xlcyI6IFtdfX19MYIBhTCCAYECAQEwXDBXMQswCQYDVQQGEwJVUzEOMAwGA1UECAwFVW5zZXQxDjAMBgNVBAcMBVVuc2V0MQ4wDAYDVQQKDAVVbnNldDEYMBYGA1UEAwwPd3d3LmV4YW1wbGUuY29tAgEBMAsGCWCGSAFlAwQCATANBgkqhkiG9w0BAQEFAASCAQAFH5pNJBnDaE08xNCq7GXcC+lPMgD3ZNOZDXAXTTKerSq3qSGF+HGQYMXlIUQsCTwTKRflumA+gFVlt4I51fXDNdbk0cgCVuzRa0YmZY829UfXbwPaRmhYRm46CPhvrS4ven8Nu2SF1ON+uK2nnqgwXLjXAwEjPnUdWQ-SfW5roPGlN6prcOUdshO2GfzWrbjl-iCsS36-3C5PVnJabO0ypKr+bBy-HGuN2sL40yXOx6tSqt6YY7wzpwQG2pCzmVc3A3lF19g5VZTGe0apBbnYc8MKXGA24uNLssRUGHd-OjVWr95dQOxiaUbvEGs2u2o18PKbvvEZdqy8fT0LKXGh"}, "serviceCatalog"=>[], "user"=>{"username"=>"admin", "roles_links"=>[], "id"=>"264916517292479691398061166cad59", "roles"=>[], "name"=>"admin"}, "metadata"=>{"is_admin"=>0, "roles"=>[]}}}, @response=#<Net::HTTPOK 200 OK readbody=true>, @headers={"vary"=>["X-Auth-Token"], "content-type"=>["application/json"], "content-length"=>["1317"], "date"=>["Tue, 10 Mar 2015 17:34:22 GMT"], "connection"=>["close"]}>
http://192.168.52.163:35357/v2.0/tenants
opening connection to 192.168.52.163...
opened
<- "GET /v2.0/tenants HTTP/1.1\r\nAccept: application/json\r\nUser-Agent: rOCCI-core/4.3.2 rOCCI-api/4.3.1 OCCI/1.1 ruby-x86_64-linux/1.9.3p484\r\nX-Auth-Token: MIIC+QYJKoZIhvcNAQcCoIIC6jCCAuYCAQExDTALBglghkgBZQMEAgEwggFHBgkqhkiG9w0BBwGgggE4BIIBNHsiYWNjZXNzIjogeyJ0b2tlbiI6IHsiaXNzdWVkX2F0IjogIjIwMTUtMDMtMTBUMTc6MzQ6MjIuNjUyMTUxIiwgImV4cGlyZXMiOiAiMjAxNS0wMy0xMFQxODozNDoyMloiLCAiaWQiOiAicGxhY2Vob2xkZXIifSwgInNlcnZpY2VDYXRhbG9nIjogW10sICJ1c2VyIjogeyJ1c2VybmFtZSI6ICJhZG1pbiIsICJyb2xlc19saW5rcyI6IFtdLCAiaWQiOiAiMjY0OTE2NTE3MjkyNDc5NjkxMzk4MDYxMTY2Y2FkNTkiLCAicm9sZXMiOiBbXSwgIm5hbWUiOiAiYWRtaW4ifSwgIm1ldGFkYXRhIjogeyJpc19hZG1pbiI6IDAsICJyb2xlcyI6IFtdfX19MYIBhTCCAYECAQEwXDBXMQswCQYDVQQGEwJVUzEOMAwGA1UECAwFVW5zZXQxDjAMBgNVBAcMBVVuc2V0MQ4wDAYDVQQKDAVVbnNldDEYMBYGA1UEAwwPd3d3LmV4YW1wbGUuY29tAgEBMAsGCWCGSAFlAwQCATANBgkqhkiG9w0BAQEFAASCAQAFH5pNJBnDaE08xNCq7GXcC+lPMgD3ZNOZDXAXTTKerSq3qSGF+HGQYMXlIUQsCTwTKRflumA+gFVlt4I51fXDNdbk0cgCVuzRa0YmZY829UfXbwPaRmhYRm46CPhvrS4ven8Nu2SF1ON+uK2nnqgwXLjXAwEjPnUdWQ-SfW5roPGlN6prcOUdshO2GfzWrbjl-iCsS36-3C5PVnJabO0ypKr+bBy-HGuN2sL40yXOx6tSqt6YY7wzpwQG2pCzmVc3A3lF19g5VZTGe0apBbnYc8MKXGA24uNLssRUGHd-OjVWr95dQOxiaUbvEGs2u2o18PKbvvEZdqy8fT0LKXGh\r\nContent-Type: application/json\r\nAuthorization: Basic YWRtaW46c3VwZXJzZWNyZXQ=\r\nConnection: close\r\nHost: 192.168.52.163:35357\r\n\r\n"
-> "HTTP/1.1 401 Unauthorized\r\n"
-> "Www-Authenticate: Keystone uri=\"http://192.168.52.163:5000/\"\r\n"
-> "Vary: X-Auth-Token\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 114\r\n"
-> "Date: Tue, 10 Mar 2015 17:34:22 GMT\r\n"
-> "Connection: close\r\n"
-> "\r\n"
reading 114 bytes...
-> "{\"error\": {\"message\": \"The request you have made requires authentication.\", \"code\": 401, \"title\": \"Unauthorized\"}}"
read 114 bytes
Conn close
D, [2015-03-10T10:34:22.757816 #68442] DEBUG -- : [rOCCI-api] #<HTTParty::Response:0x1798c30 parsed_response={"error"=>{"message"=>"The request you have made requires authentication.", "code"=>401, "title"=>"Unauthorized"}}, @response=#<Net::HTTPUnauthorized 401 Unauthorized readbody=true>, @headers={"www-authenticate"=>["Keystone uri=\"http://192.168.52.163:5000/\""], "vary"=>["X-Auth-Token"], "content-type"=>["application/json"], "content-length"=>["114"], "date"=>["Tue, 10 Mar 2015 17:34:22 GMT"], "connection"=>["close"]}>
/var/lib/gems/1.9.1/gems/occi-api-4.3.1/lib/occi/api/client/http/authn_plugins/keystone.rb:110:in `get_first_working_tenant': Keystone didn't return any tenants, fallback failed! (Occi::Api::Client::Errors::AuthnError)
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.1/lib/occi/api/client/http/authn_plugins/keystone.rb:20:in `setup'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.1/lib/occi/api/client/http/helpers.rb:39:in `get_auth'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.1/lib/occi/api/client/http/helpers.rb:56:in `rescue in preauthenticate'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.1/lib/occi/api/client/http/helpers.rb:46:in `preauthenticate'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.1/lib/occi/api/client/client_base.rb:44:in `initialize'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.1/lib/occi/api/client/client_http.rb:46:in `initialize'
	from occi_test.rb:26:in `new'
	from occi_test.rb:26:in `<main>'
```
I didn't do much configuration on OpenStack, it is just a DevStack that I install to work with Occi-os and I tested with a few Occi command sent with curl. If I understand the log, it seems to get a authentication token but fail when it try to get the tenant ?

Thanks

**Comment by arax** [comment]
Exactly, it looks like your OCCI-OS endpoint has the wrong Keystone URI in configuration. Or at least the wrong port number ... You need to set `auth_uri` somewhere in your configuration to 'http://192.168.52.163:5000'. Maybe in `nova.conf`? I'm not sure.
~~~
-> "Www-Authenticate: Keystone uri='http://192.168.52.163:35357'"
~~~

**Comment by Alex134** [comment]
After some research, it looks like there two services api: admin and public.
http://192.168.52.163:35357 is the admin url while while http://192.168.52.163:5000 is the public url.
It looks like it authenticates itself on the admin url, and then tries to get the tenant on the public one, I tries switching to another user, but it doesn't seem to make a difference.

**Comment by arax** [comment]
Switching to a different user won't help. You have to configure your services (OpenStack services, especially OCCI-OS) to authenticate against the public Keystone URL only. Every user authentication request has to go to http://192.168.52.163:5000.

You need to change (or add) 'auth_uri' in your nova.conf!

**Comment by arax** [comment]
No response. Closing.
